services:
  - type: web
    name: aviator-rng-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    autoDeploy: true
    branch: main
    plan: free
